<?php

namespace RPGBundle\Repository;

/**
 * PersonOnMapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonOnMapRepository extends \Doctrine\ORM\EntityRepository
{
}
