<?php

namespace RPGBundle\Repository;

/**
 * QuestStepsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestStepsRepository extends \Doctrine\ORM\EntityRepository
{
}
